// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package fronted

import (
	"word_whisper_end/api/fronted"
)

type UserControllerV1 struct{}

func NewUserV1() fronted.IUserV1 {
	return &UserControllerV1{}
}

type HomeControllerV1 struct {
}

func NewHomeV1() fronted.IHomeV1 {
	return &HomeControllerV1{}
}
