// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"word_whisper_end/internal/dao/internal"
)

// internalUserWordsDao is internal type for wrapping internal DAO implements.
type internalUserWordsDao = *internal.UserWordsDao

// userWordsDao is the data access object for table user_words.
// You can define custom methods on it to extend its functionality as you wish.
type userWordsDao struct {
	internalUserWordsDao
}

var (
	// UserWords is globally public accessible object for table user_words operations.
	UserWords = userWordsDao{
		internal.NewUserWordsDao(),
	}
)

// Fill with you ideas below.
