// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"word_whisper_end/internal/dao/internal"
)

// internalUserProgressDao is internal type for wrapping internal DAO implements.
type internalUserProgressDao = *internal.UserProgressDao

// userProgressDao is the data access object for table user_progress.
// You can define custom methods on it to extend its functionality as you wish.
type userProgressDao struct {
	internalUserProgressDao
}

var (
	// UserProgress is globally public accessible object for table user_progress operations.
	UserProgress = userProgressDao{
		internal.NewUserProgressDao(),
	}
)

// Fill with you ideas below.
